fruits_seassonal=["Banana","Orange","Apple","Mango","Water Melon"];

console.log("------------------------1st-----------------------------");
console.log(fruits_seassonal[0]);
console.log(fruits_seassonal[fruits_seassonal.length-1]);
console.log("---------------------2nd---------------------------------");
fruits_seassonal[0]="Papaya";
console.log(fruits_seassonal);
console.log("----------------------3rd--------------------------------");
fruits_seassonal.splice(3,1);
console.log(fruits_seassonal);
console.log("------------------------4th-------------------------------");
fruits_seassonal.push("Pineapple");
console.log(fruits_seassonal);
console.log("-------------------------5th---------------------------------");
let splicedElements=fruits_seassonal.splice(3,0,"Dragon Fruits");
console.log(fruits_seassonal);
console.log("-----------------------6th--------------------------------");
slicedElements=fruits_seassonal.splice(1,1,"Kiwi");
console.log(fruits_seassonal);
console.log("--------------------------------7th----------------------------");
console.log(fruits_seassonal.slice(1,5));
console.log("------------------------------8th----------------------------------");
console.log(fruits_seassonal.splice(fruits_seassonal.length-3));